services:
  frontend:
    build:
      context: .
      args:
        RESEND_API_KEY: "re_62GwbQ8T_8uwxnc3zbwMnKtweYEPkMj1M"
    image: hoaitran_portfolio_frontend
    container_name: hoaitran_portfolio_frontend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
