services:
  frontend:
    build:
      context: .
      args:
        RESEND_API_KEY: "resend-api-key"
    image: hoaitran_portfolio_frontend
    container_name: hoaitran_portfolio_frontend
    ports:
      - "5000:3000"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
